### ISSUE TITLE
Bugs with right clicking a Shulker Box inside another inventory

### ISSUE THREAD

**Issue by maruohon** [kyrptonaught/quickshulker#22]
If you have identical Shulker Boxes (color and contents, presumably full NBT check) in the player inventory and also in another inventory such as a regular Chest or an Ender Chest, and you right click on the box in the other inventory (Chest), then the box in your player inventory will be opened instead.

Also related to this, if you right click on a box in that other inventory that is NOT in your player inventory, then the server console will print out error messages like this:
```
[10:34:20] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: null
```

Also a bit earlier I got this message, but now I can't reproduce it, not entirely sure what I did there:
```
[10:17:38] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_241]
        at net.minecraft.class_2371.get(class_2371.java:46) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.class_1661.method_5438(class_1661.java:511) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.kyrptonaught.quickshulker.api.Util.openItem(Util.java:31) ~[quickshulker-1.16.5-1.1.12.jar:?]
        at net.kyrptonaught.quickshulker.OpenShulkerPacket.lambda$registerReceivePacket$0(OpenShulkerPacket.java:20) ~[quickshulker-1.16.5-1.1.12.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft_server_1.16.5.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

**Comment by kyrptonaught** [comment]
This should now be fixed as of 1.1.13
