### ISSUE TITLE
Crash on launch when attempting to use this mod with optifine/optifabric

### ISSUE THREAD

**Issue by Toast732** [kyrptonaught/quickshulker#55]
**Versions Used:**

Game Version: `1.19`
Fabric Loader Version: `0.14.8-1.19`
Fabric API Version: `0.56.3+1.19`
Optifabric Version: `1.13.5`
Tested Optifine Versions: `H9_pre1, H8_pre9 and H8`
Quickshulker Version: `1.3.6-1.19`

**Info:**
Using optifine and optifabric with this mod would cause the game to crash while after launching the game. I tried with just these 4 mods enabled (fabric API, optifabric, optifine and Quickshulker) and it crashed. without quick shulker the game does not crash, and if I keep quick shulker but remove optifine and optifabric then it will also not crash. I've tested multiple versions of optifine to ensure that its not just an issue with a specific version of optifine.

If it helps any, here's the crash info printed:
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173)
	at net.minecraft.class_128.method_24305(class_128.java:343)
	at net.minecraft.client.main.Main.main(Main.java:152)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_315 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:499)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector spoofDisplayOnlyKeyBinds(Lnet/minecraft/class_304;)Ljava/lang/String; in net.kyrptonaught.kyrptconfig.json:displaykeybind.GameOptionsMixin from mod kyrptconfig failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kyrptconfig-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more
```

**Comment by kyrptonaught** [comment]
This is a crash from my config library. See more info here: https://github.com/kyrptonaught/CMDKeybinds/issues/25#issuecomment-1186792829

**Comment by kyrptonaught** [comment]
Here is a test build. This may crash with some of my other mods
[quickshulker-1.3.7-1.19 PRERELEASE.zip](https://github.com/kyrptonaught/quickshulker/files/9130010/quickshulker-1.3.7-1.19.PRERELEASE.zip)

**Comment by Toast732** [comment]
sorry for extremely late response, completely forgot lol

but this version works perfectly with optifine, thanks!

**Comment by kyrptonaught** [comment]
This version was released
