### ISSUE TITLE
1.20.2: crash when opening config; crash when opening ender chest on server

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/quickshulker#82]
The following two defect are found when using version 1.5.0 on MC 1.20.2

1. crash when opening config (via modmenu 8.0)
```
Caused by: java.lang.NoSuchFieldError: field_22757
	at net.kyrptonaught.kyrptconfig.config.screen.NotSuckyButton.method_48579(NotSuckyButton.java:26) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:73) ~[client-intermediary.jar:?]
	at net.kyrptonaught.kyrptconfig.config.screen.items.ConfigItem.render(ConfigItem.java:157) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
	at net.kyrptonaught.kyrptconfig.config.screen.items.KeybindItem.render(KeybindItem.java:67) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
	at net.kyrptonaught.kyrptconfig.config.screen.ConfigSection.render(ConfigSection.java:108) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
	at net.kyrptonaught.kyrptconfig.config.screen.ConfigScreen.method_25394(ConfigScreen.java:108) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
```
2. crash when opening an ender-chest (right click in inventory) on a server (crashes the server)
```
[19:45:01] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_1735.method_48931(net.minecraft.class_1799)'
	at net.kyrptonaught.quickshulker.BundleHelper.unbundleStackIntoSlot(BundleHelper.java:38) ~[quickshulker-1.4.0-1.20.jar:?]
	at net.minecraft.class_1792.handler$cag000$quickshulker$QS$onStackClicked(class_1792.java:2059) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.method_31565(class_1792.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.method_31575(class_1799.java:407) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_45409(class_1703.java:530) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java:408) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1640) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbh000$carpet$modifiedRunLoop(MinecraftServer.java:7460) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by Adogs1** [comment]
所以还会有1.20.2更新吗

**Comment by Adogs1** [comment]
> The following two defect are found when using version 1.5.0 on MC 1.20.2
> 
> 1. crash when opening config (via modmenu 8.0)
> 
> ```
> Caused by: java.lang.NoSuchFieldError: field_22757
> 	at net.kyrptonaught.kyrptconfig.config.screen.NotSuckyButton.method_48579(NotSuckyButton.java:26) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
> 	at net.minecraft.class_339.method_25394(class_339.java:73) ~[client-intermediary.jar:?]
> 	at net.kyrptonaught.kyrptconfig.config.screen.items.ConfigItem.render(ConfigItem.java:157) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
> 	at net.kyrptonaught.kyrptconfig.config.screen.items.KeybindItem.render(KeybindItem.java:67) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
> 	at net.kyrptonaught.kyrptconfig.config.screen.ConfigSection.render(ConfigSection.java:108) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
> 	at net.kyrptonaught.kyrptconfig.config.screen.ConfigScreen.method_25394(ConfigScreen.java:108) ~[kyrptconfig-1.5.4-1.20-238de7773c4ed271.jar:?]
> 	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
> ```
> 
> 2. crash when opening an ender-chest (right click in inventory) on a server (crashes the server)
> 
> ```
> [19:45:01] [Server thread/ERROR]: Encountered an unexpected exception
> java.lang.NoSuchMethodError: 'void net.minecraft.class_1735.method_48931(net.minecraft.class_1799)'
> 	at net.kyrptonaught.quickshulker.BundleHelper.unbundleStackIntoSlot(BundleHelper.java:38) ~[quickshulker-1.4.0-1.20.jar:?]
> 	at net.minecraft.class_1792.handler$cag000$quickshulker$QS$onStackClicked(class_1792.java:2059) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1792.method_31565(class_1792.java) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1799.method_31575(class_1799.java:407) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1703.method_45409(class_1703.java:530) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1703.method_30010(class_1703.java:408) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3244.method_12076(class_3244.java:1640) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.handler$zbh000$carpet$modifiedRunLoop(MinecraftServer.java:7460) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
> 	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
> ```

我测试了在服务器上右键打开末影箱并不会使服务器崩溃

**Comment by JoshCode** [comment]
Late reply, but number 2 seems to be related to the following config settings:

```
// file: .minecraft\config\quickshulkerconfig.json5

// Right Clicking a shulker with an item inserts it
"supportsBundlingInsert": true,
// Right Clicking an item with a shulker inserts it
"supportsBundlingPickup": true,
// Right Clicking an empty slot with a shulker extracts an item
"supportsBundlingExtract": true,
```

I was also experiencing a bug where, when a shulker is held under the cursor, right-clicking on an inventory would crash the game (or the server if multiplayer).
Changing all of these config settings to false, I was not able to replicate the bug anymore.

#84 is probably also related to the same bug.

**Comment by MeeniMc** [comment]
This is unmaintained, I have moved to https://modrinth.com/mod/easy-shulker-boxes which is not exacly the same thing but doesn't have dupes.

**Comment by Adogs1** [comment]
> 这是无维护的，我已经搬到[了 https://modrinth.com/mod/easy-shulker-boxes](https://modrinth.com/mod/easy-shulker-boxes) 它不完全是一回事，但没有复制。

如果我需要使用1.21版本，我应该寻找哪个分支？
